---
title: "Outreach"
page-layout: article
listing:
  contents: outreach
  type: grid           # <--- Switches from simple list to "Card/Box" mode
  grid-columns: 1      # <--- Forces the box to be wide (full width)
  grid-item-border: true
  sort: "date desc"
  categories: true
  #image: false         # <--- Important! Hides the "grey box" since you don't have photos
  fields: [date, title, description, categories]
  filter-ui: false
  sort-ui: false
---

I regularly give talks at high school, create research projects with high school students, and lead math events for the local community. I also give public lectures at the New York Public Library, collaborate as a mentor with New York Academy of Sciences, Pioneer Academy, and Center for Mathematical Talent. Several high school students I have done research projects with, have been semi finalists in the INTEL Science Competition. 

- **ArchaeoHack (2025)**: Mentor and judge for the inaugural ArchaeoHack 2025. The topic was to create an app that recognizes Egyptian Hieroglyphs as images or sketched by hand.

- **CSPLASH (2021 onwards)**: Math Society volunteers organized annual day-long event for highschool students; talks by faculty, lab visits, and games.

- **Girls in STEM (GSTEM)**: A Courant Institute Summer research program for female high school students in the US. Participated as research mentor in 2013, 2014, 2015, 2016.

- **New York Public Library (NYPL)**: Gave two lecture series (5 lectures each) at the Jefferson Branch. (Spring 2016) Mathematical Patterns In Nature, (Fall 2016) Physics of Everyday Things.

- **New York Academy of Sciences (NYAS) 2017-2021**: 

   + *Global Science Academy*: As a research mentor, I mentored research team composed of high school students around the world on   
      research projects (online, 2017, 2018).

   + *Scientist-In-Residence*: Mentored 7th and 8th grade classes in New York Public Schools on research projects for one semester. 
      PS-181 in Fall 2017 and PS-151 in Fall 2018. 

   + *After-School Program (2019)*: Participated in after school program for 2nd, 3rd, and 4th grade students, guiding them through 
     activities and experiments.    

- **NYU-ABU DHABI**: Mentoring and teaching talented Emerati high school students in Abu Dhabi (Summer 2017).

- **Center for Mathematical Talent**: Lecture Series on Graph Theory for talented high school students in NYC (2016, 2018, 2020, 2022).
