---
title: "Research"
page-layout: article
---

## Past and Current Research

My primary area is soft matter physics. In particular, I have worked on granular physics, complex fluids, and fluid-structure interactions in the swimming locomotion of *C. elegans*. 

**Recently, I have been exploring problems at the intersection of Math, Physics, and Deep Learning. My primary motivation for research is to use it as a teaching tool to introduce undergrads and high school students to critical thinking, research methods, systematic exploration, and science communication.**

::: {.panel-tabset}

## Professional

My primary area falls broadly under the label of "soft matter physics". In particular, my Ph.D. was on granular physics. I solved teh highly complex and seemingly intractable inverse problem of finding contact forces on particles from photoelastic images. My Ph.D. work was considered groundbreaking, that resulted in my very first publication in Nature. A follow up work on jamming in granular media was published in Physical Review Letters as a Cover Article. 


## Undergrad
(Put your undergrad text/images here)

## High School
(Put your HS text/images here)

:::
