---
title: "Mathematical Patterns in Nature"
date: 2017-09-02
categories: [Public Lecture, New York Public Library]
description: "A lecture course (5 lectures) given at the New York Public Library, Jefferson Branch, about mathematical patterns that naturally emerge in nature, from arrangement of petals to galaxies, and some real world applications."
---

## Abstract

In this series of lectures, we will explore how similar mathematical patterns emerge; from galaxies to atoms, in art and in finance. We will first explore how certain numbers like “pi” and “e” keep appearing in diverse fields. [cite_start]We will see how numbers and their sequences give an underlying mathematical structure to different problems.

Next we will examine the role of randomness in mathematics and our lives. We will see how from this randomness emerges a regular pattern - the famous “Bell Curve”. We will investigate its uses in different situations. We will then explore how mathematics allows us to deconstruct complex situations involving decision-making. How do we come up with a method for fair distribution, be it for property, or corporate merger, or organ transplant.

[cite_start]In the fourth lecture, we will study an unusual system of arithmetics called “modular arithmetic”, which allows us to use prime numbers to create the ubiquitous security and code systems that are in every bar code, every credit card - the so called “RSA encryption”.

Finally, we will study the world of graphs and networks: similar patterns and properties emerge in networks of different types, from airline routes to electrical grids. We will also see the use of graph theory to solve minimal cost, minimal time, shortest path, and task-scheduling problems.

## Event Details

**Location:** Jefferson Branch, Manhattan
**Audience:** All ages.